### ISSUE TITLE
Error Message in Mines

### ISSUE THREAD

**Issue by amburo** [misty-spring/StardewMods#3]
Here's the smapi log: https://smapi.io/log/6fe6b03e4cda4df9af5c299455a2de5f
(the reported outdated mods are all currently updated, they were manifest issues.)

An error message repeats in the console each level of the regular mines I descend down. Doesnt seem to cause any in-game problems outside of said error logging but I am unsure if something more is happening under the hood.

**Comment by misty-spring** [comment]
The error was in the code that replaces mineshaft spawns- the only consequence is that its ores weren't replaced

Fixed in version 1.1.1
