### ISSUE TITLE
[Request] Expose ResourceData in the ItemExtensions API

### ISSUE THREAD

**Issue by justastranger** [misty-spring/StardewMods#4]
I decided to add custom clump support when re-implementing clump breaking for an unofficial BetterBombs update and this resulted in a hard dependency on ItemExtensions so that I could access and read the items that should be dropped. Having a way to retrieve this `ResourceData` object by the clump ID using the API would allow me to make the dependency optional and safer.

**Comment by misty-spring** [comment]
Done- 1.6 adds an API method to get ResourceData as object.
If anything comes up, let me know
