### ISSUE TITLE
[Item Extensions] Volcano node spawns also spawn in normal Mines

### ISSUE THREAD

**Issue by UncleArya** [misty-spring/StardewMods#6]
Hello Misty. A user reported an issue with my Resource Chickens mod that I think is possibly a bug with Item Extensions, unless I am misunderstanding the intention (which could be possible). I did some testing and I was able to replicate it.

Expected behaviour: Setting `"Type": "Volcano"` within MineSpawns will spawn nodes only in the Volcano mines and not in the normal mines or skull cavern.

Current behaviour: Nodes do spawn in the Volcano as intended, but also on the corresponding floors within the normal mines.

I have added a workaround by adding `!LOCATION_IS_MINES Here` to the spawn condition.

```
{
	"Action": "EditData",
	"Target": "Mods/mistyspring.ItemExtensions/Resources",
	"Entries": {				
		"{{ModId}}.VolcanoMineVolcanoEgg": {
			"DisplayName": "Volcano Egg Node",
			"Type": "Stone",
			"Texture": "{{ModId}}/Items",
			"SpriteIndex": 3,
			"Width": 1,
			"Height": 1,
			"Health": 12,
			"Tool": "Pickaxe",
			"ItemDropped": "{{ModId}}.VolcanoEgg",
			"MinDrops": 1,
			"MaxDrops": 1,
			"Debris": "stone",
			"Sound": "hammer",
			"BreakingSound": "stoneCrack",
			"MineSpawns": [
				{
					"Floors": "1/9",
					"Type": "Volcano",
					"Condition": "PLAYER_MINING_LEVEL Current 8",
					"SpawnFrequency": 0.003
				}
			]
		}
	}
}
```

**Comment by misty-spring** [comment]
Hi UncleArya, thank you for the patience!
In 1.6.1 mineshaft ignores any spawns that are set as "volcano"
