### ISSUE TITLE
Tool type for breaking resources via API

### ISSUE THREAD

**Issue by AlanDavison** [misty-spring/StardewMods#9]
Hi, and sorry for creating this issue! I didn't want to DM you on Discord because it's technically not about a commission.

I'm trying to get Item Extensions support in Smart Cursor, but it seems like the only reliable way I can determine which tool can break a given resource (except for pickaxes, which I imagine to be doable via `IsStone()` in the API) is to use `GetResourceData()` in the API, but without knowing how much of a moving target the resource model is, I'm slightly wary.

Would you maybe be open to a PR to add a `GetBreakingTool(string id)` method to the API? I'd be more than happy to do that myself!

**Comment by misty-spring** [comment]
No worries! 
I've made the resource model as consistent as possible: the only changes are additions, existing properties aren't touched.

You could get `GetResourceData`'s Tool, since that's what the method would return.

If you're still unsure, I can add it to the API

**Comment by AlanDavison** [comment]
Sorry for taking so long to get back around to this! If the model will remain consistent as far as existing fields go, I can absolutely just use it as-is.

Feel free to close this out!

**Comment by misty-spring** [comment]
Sure! 
Just in case, in 1.11.0 I added `GetBreakingTool`.
